services:
  honeypot:
    image: ghcr.io/lockness-ko/xz-vulnerable-honeypot:latest
    build: .
    ports:
      - "2222:22"
    userns_mode: "host"
    privileged: true
    volumes:
      - ./logs:/logs
      - /sys/kernel/debug:/sys/kernel/debug
